### PR TITLE
Fix filter_paths() to not partial match paths

### PR DESCRIPTION
**Pull request by nsoranzo**
E.g. in https://github.com/galaxyproject/tools-iuc/pull/1278 having 'tools/taxonomy' in `.tt_blacklist` and executing `planemo ci_find_repos --exclude_from .tt_blacklist` wrongly filters out also 'tools/taxonomy_krona_chart'.

### CODE REVIEW

**Comment by jmchilton** [comment]
Sorry about that - thanks for the fix! I guess I should convert those to regex or globs perhaps.

**Comment by nsoranzo** [comment]
Hopefully we'll remove all tools from the blacklist before that is needed :)

**Comment by nsoranzo** [comment]
@jmchilton Can you do a release with this included? It's needed for https://github.com/galaxyproject/tools-iuc/pull/1278 .

**Comment by jmchilton** [comment]
@nsoranzo 0.40.1 is now available on PyPI.

**Comment by nsoranzo** [comment]
Thanks @jmchilton, https://github.com/galaxyproject/tools-iuc/pull/1278 is now fixed!

**Pull request merged**
