### PR TITLE
Shed diff report

### PR DESCRIPTION
**Pull request by erasche**
This produces a (fake) XUnit report for the shed_diff command. It's not complete as-is, but it'll provide essential functionality immediately. The XUnit reports will tell you if a shed diff returned a repository as being identical, different (failure), or if the diff command failed (error). It will not show a copy of the diff as I couldn't figure out how to cleanly extract that.

@jmchilton if you have suggestions for [how this should be better implemented](https://github.com/galaxyproject/planemo/commit/9813ef0c1e2e249e35dc85ada8b713eae405b43a), please let me know. I see that most of the commands are pretty small and most of that functionality is tucked away in `planemo.shed` and friends, but here I went with the implementation I was comfortable with. If you have suggestions how I should get at the diff output I'd be happy to make another PR with those (or update this one).

- [x] Depends on #304 

(I branched off of that branch, I didn't want to deal with merge issues since these both needed common changes to the code, blargh.)

### CODE REVIEW

**Comment by erasche** [comment]
Ping @martenson, this will make the shed tests much easier to read. :)

**Comment by erasche** [comment]
Will get failing test cases figured out presently.

**Comment by jmchilton** [comment]
Let me know if you need help with the test cases, otherwise this looks very good to me. Thanks @erasche.

**Comment by erasche** [comment]
@jmchilton got my issue figured out :) Also adding test cases for new shed_diff xunit report. Will push shortly.

**Comment by erasche** [comment]
Okay, I'm at a loss for why my tests are still failing when they aren't locally. I'll attack this some more tomorrow.

**Comment by jmchilton** [comment]
Yeah, they work locally for me too. Pushed a small tweak to the test cases that should improve the assertion error message reporting.

**Comment by erasche** [comment]
(TIL you can run individual tox tests with `tox -e py27 -- -s --tests tests.test_shed_diff`. Also will squash before this gets merged due to unnecessary number of commits because of Travis)

**Comment by erasche** [comment]
<expletives> It finally passes! Whuuuu! @jmchilton haha. Sorry, just been wrestling with this for days and to find out it was all because of stupid non-deterministic library methods...

**Comment by jmchilton** [comment]
Brilliant, thanks a bunch @erasche.

**Pull request merged**
