### PR TITLE
Update github commands to authenticate with a token rather than username/password

### LINKED ISSUE #1082: Do not authenticate planemo pull_request with github password
Currently `planemo pull_request` relies on a github username and password being specified in the .planemo.yml file. This should be changed due to https://github.blog/2020-07-30-token-authentication-requirements-for-api-and-git-operations/.

I'll have a look at this since we need this for our autoupdate bot.

### PR DESCRIPTION
**Pull request by simonbray**
Fixes #1082.

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]

**Comment by mvdbeek** [comment]
This does mean we'll have to update planemo-monitor with the next release. Is that ok with you @bgruening @jmchilton ?

**Comment by simonbray** [comment]
As far as I understand Github will no longer allow authentication from the command line with username+password, so this would be necessary anyway.

**Comment by mvdbeek** [comment]
That's definitely still working, as we're getting new mulled PRs. I think the deadline is November 13th, 2020. It's not a big deal, we just need to be ready to make the switch.

**Comment by bgruening** [comment]
Ok, I can dedicate some time to this and fix it.

:+1: from my side.

**Pull request merged**
