### PR TITLE
Update pinning for Galaxy 24.1

### PR DESCRIPTION
**Pull request by bernt-matthias**
Ping @jdavcs can you retrigger CI here once you created the packages for 24.1? No need to hurry.

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]

**Comment by jdavcs** [comment]
@bernt-matthias 24.1.1 packages published, CI triggered.

**Comment by bernt-matthias** [comment]
Thanks a lot.

**Review by mvdbeek — APPROVED** [review]
Want to pull it out of draft @bernt-matthias ?
I would create a new planemo package after that.

**Comment by bernt-matthias** [comment]
> I would create a new planemo package after that.

Excellent

**Pull request merged**
