### PR TITLE
Drop call to ``escape_non_unicode_symbols``

### PR DESCRIPTION
**Pull request by nsoranzo**
which was removed from allure-python-commons in 2.13.0 .

Alternative to https://github.com/galaxyproject/planemo/pull/1356 .

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]

**Comment by nsoranzo** [comment]
Looking at the error message, I think the failing test is due to https://github.com/galaxyproject/galaxy/pull/15497 , ping @nuwang .

**Comment by mvdbeek** [comment]
Thanks @nsoranzo!

**Comment by nsoranzo** [comment]
Hi @nuwang , thanks for getting back! Yes, I think so, see this test run (line 2546): https://github.com/galaxyproject/planemo/actions/runs/4365276747/jobs/7633682776#step:8:2547

```
galaxy.tool_util.provided_metadata INFO 2023-03-08 14:56:58,940 [pN:main.1,p:10159,tN:LocalRunner.work_thread-0] One or more tool outputs is marked as failed ({'type': 'dataset', 'ext': 'data', 'dataset_id': 1, 'stderr': 'Unable to fetch file:///home/runner/work/planemo/planemo/tests/data/hello.txt\nCould not find handler for URI [file:///home/runner/work/planemo/planemo/tests/data/hello.txt]', 'failed': True}).
```

It seems the `file://` protocol is not correctly handled. If you can take a look, that would be great!

**Comment by nuwang** [comment]
I think I see where the issue is originating from and adding file:// as a supported protocol should restore previous behaviour. I'll create a PR with a fix.

**Comment by nsoranzo** [comment]
> I think I see where the issue is originating from and adding file:// as a supported protocol should restore previous behaviour. I'll create a PR with a fix.

That's great, thanks @nuwang !

**Pull request merged**
