### PR TITLE
Some fixes for workflow_job_init and workflow_test_init

### PR DESCRIPTION
**Pull request by simonbray**
- Recognize the input types as specified by gxformat2 here: https://github.com/galaxyproject/gxformat2/blob/master/gxformat2/model.py#L66
- Add parameters
- Add a more helpful error message for unlinted workflows

### CODE REVIEW

**Comment by bgruening** [comment]
Can you please add a test, so we do not regress here anymore? Thanks.

**Comment by simonbray** [comment]
> Can you please add a test, so we do not regress here anymore? Thanks.

There is a test already, but you are right, I need to make it stricter.

Also, these commands don't work yet with workflow IDs, it would be good to get that working.

**Comment by simonbray** [comment]
> Also, these commands don't work yet with workflow IDs, it would be good to get that working.

I will leave this for now.

**Comment by jmchilton** [comment]
Sorry for missing this! Feel free to ping me on these Planemo PRs for potentially quicker turn around.

**Comment by simonbray** [comment]
No worries, thanks for the merge!

**Pull request merged**
