### PR TITLE
Better use of conditional requirements.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by peterjc** [comment]
As noted on https://github.com/galaxyproject/galaxy/issues/1571 while trying to test Galaxy Tools with Planemo under Python 2.6, my TravisCI setup accidentally pulled in cwltool which targets Python 2.7

(This was discovered during testing of pull request https://github.com/peterjc/galaxy_blast/pull/77 against the Galaxy BLAST+ wrappers)

**Comment by jmchilton** [comment]
@peterjc How's your pip-foo - any clue if this tweak will prevent ``pip install planemo`` from pulling in cwltool on Python 2.6?

**Comment by peterjc** [comment]
Note sure - I'd be turning to Google or experimenting to try to answer that, sorry.

**Comment by peterjc** [comment]
My TravisCI setup still breaks with Python 2.6 and Galaxy dev branch due to wrongly pulling in cwltool, https://travis-ci.org/peterjc/galaxy_blast/builds/107255015 gave (at time of writing):

```
$ python ./scripts/functional_tests.py -v `python tool_list.py Continuous-Integration-Travis`
Traceback (most recent call last):
  File "./scripts/functional_tests.py", line 30, in <module>
    from galaxy.app import UniverseApplication
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/app.py", line 24, in <module>
    from galaxy.visualization.plugins.registry import VisualizationsRegistry
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/visualization/plugins/registry.py", line 15, in <module>
    from galaxy.visualization.plugins import plugin as vis_plugins
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/visualization/plugins/plugin.py", line 13, in <module>
    from galaxy.web.base import interactive_environments
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/web/base/interactive_environments.py", line 13, in <module>
    from galaxy.tools.deps.docker_util import DockerVolume
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/tools/__init__.py", line 26, in <module>
    from galaxy.tools.actions import DefaultToolAction
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/tools/actions/__init__.py", line 7, in <module>
    from galaxy.tools.parameters.basic import DataCollectionToolParameter, DataToolParameter
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/tools/parameters/__init__.py", line 5, in <module>
    from basic import DataCollectionToolParameter, DataToolParameter, SelectToolParameter
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/tools/parameters/basic.py", line 18, in <module>
    import galaxy.tools.parser
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/tools/parser/__init__.py", line 4, in <module>
    from .factory import get_tool_source
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/tools/parser/factory.py", line 8, in <module>
    from .cwl import CwlToolSource
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/tools/parser/cwl.py", line 14, in <module>
    from galaxy.tools.cwl import tool_proxy
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/tools/cwl/__init__.py", line 1, in <module>
    from .parser import tool_proxy
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/tools/cwl/parser.py", line 12, in <module>
    from .cwltool_deps import (
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/tools/cwl/cwltool_deps.py", line 11, in <module>
    from cwltool import (
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/cwltool/main.py", line 391
    job_order_object.update({namemap[k]: v for k,v in cmd_line.items()})
                                             ^
SyntaxError: invalid syntax
```

[For anyone reading this later, I might re-run the TravisCI test which would use the latest planemo etc on pip, so the error might go away]

At some point I plan to update my ``.travis.yml`` to use ``planemo test`` which might also help here.

**Comment by peterjc** [comment]
Filed #411 for the observed symptom this PR was trying to fix.

**Pull request merged**
