### PR TITLE
Bump galaxy package requirements to allow for 23.0

### PR DESCRIPTION
**Pull request by bernt-matthias**
TODO..

- [x] rerun after 23.0 packages available

### CODE REVIEW

**Comment by mvdbeek** [comment]
Cool, the only failure left doesn't look to be related to the packages.

**Comment by mvdbeek** [comment]
Thanks @bernt-matthias! Should we create a new release ?

**Comment by bernt-matthias** [comment]
Sure. https://github.com/galaxyproject/planemo/pull/1370 will fix weekly CI at IUC. And there is at least one PR at IUC that needs the new tool_util functionality.

**Comment by mvdbeek** [comment]
✅  https://pypi.org/project/planemo/0.75.8/

**Pull request merged**
