### PR TITLE
Omit shed_upload.tar.gz from shed_upload.tar.gz

### PR DESCRIPTION
**Pull request by davebx**

### CODE REVIEW

**Comment by bgruening** [comment]
:+1: We could probably also add ` "tool_test_output.json`

**Comment by erasche** [comment]
:+1: to both

**Comment by davebx** [comment]
Good point, @bgruening. Adding that now.

**Comment by bgruening** [comment]
Perfect! @jmchilton ready to merge!

**Comment by jmchilton** [comment]
Awesome - thanks @davebx.

**Pull request merged**
