### PR TITLE
Implement new command ``conda_lint``

### PR DESCRIPTION
**Pull request by jmchilton**
Lints conda recipes.

### CODE REVIEW

**Comment by bgruening** [comment]
I saw also your github PR and now this one and I'm wondering about your plans. Do you really think planemo should do everything?
I see benefits of having these kind of functionality in this project but I'm not sure this is a good idea. Upstream has tools for this, upstream has a community around this, why can planemo not just point to these resources.
Everything gets more and more complex over time. We will joint conda-forge soon and then not every tool should go to bioconda. linting of tools can depend on the upstream project, every channel seems to have there own build-infrastructure ...

Just wondering about KISS!?

**Comment by jmchilton** [comment]
You made issue about easing pull requests - it was your idea :wink:. Anyway - I'm perhaps worried if that other PR was overreach but I think this one is solid. It wasn't my idea to add recipe creation to planemo, but if we are going to do that (and it is cool that we will be able to build tools and recipes together with one shot with the Bioconductor stuff) then we should have a way to lint, build, and that IMO.

As for upstream having tools to do this - fantastic -  this **heavily** leverages anaconda-verify for linting recipes. Almost all the logic is still from that library. This adds that planemo polish I think - the documentation, the command-line options (options to skip various things, pick a log and error level), easier installation because it is on PyPI, prints information about the recipe, better output in general. In the future this will tie into the XUnit stuff and have all of Planemo's options for output creation and tying in with CI systems.

If conda-forge and other infrastructure and documentation efforts are going to use anaconda-verify instead of this - I can live with that - but I want to compete :smile:.

I am for KISS - KISS for the user - one planemo tool_init command that creates the tool, lints the tool, tests the tool, creates recipes, lints the recipes, test the recipes - all from one command. Along with unified documentation and command-line option handling.

**Comment by bgruening** [comment]
> You made issue about easing pull requests - it was your idea :wink:. 

I know I have sometime strange idea. I would really like to have a webinterface for planemo to assemble a Galaxy tool, click a button check everything, test everything and submit it. But how realistic is this? :(

> Anyway - I'm perhaps worried if that other PR was overreach but I think this one is solid. It wasn't my idea to add recipe creation to planemo, but if we are going to do that (and it is cool that we will be able to build tools and recipes together with one shot with the Bioconductor stuff) then we should have a way to lint, build, and that IMO.

Recipe creation is not that simple and automatized. We still need to understand how things work and BioC in particular. I'm worried that we conveying everything is so simple, just run and you have a PR ... but the real world looks in many cases very different.

> As for upstream having tools to do this - fantastic -  this **heavily** leverages anaconda-verify for linting recipes. Almost all the logic is still from that library. This adds that planemo polish I think - the documentation, the command-line options (options to skip various things, pick a log and error level), easier installation because it is on PyPI, prints information about the recipe, better output in general. In the future this will tie into the XUnit stuff and have all of Planemo's options for output creation and tying in with CI systems.

I understand and this vision is great it sounds pretty much like the web interface above, but how realistic is this, how many users will use this, it is worth to maintain such large chunks of code?

> If conda-forge and other infrastructure and documentation efforts are going to use anaconda-verify instead of this - I can live with that - but I want to compete :smile:.

Oh I have there a few ideas where you can compete with others ;)

> I am for KISS - KISS for the user - one planemo tool_init command that creates the tool, lints the tool, tests the tool, creates recipes, lints the recipes, test the recipes - all from one command. Along with unified documentation and command-line option handling.

Understandable, but I guess I'm more realistic now after numerous fights with dependencies and build-infrastructures. To test a recipe properly you will need Docker very soon and a mulled like architecture, nothing impossible but is this is not at all PyPI install able and requires more work.

I think it's the usual Björn problem, I share your vision but I would like to keep tools simple.
For example this engineering effort would imho be better spend in automatically generating conda packages for all BioC libraries. With this you would not need this feature here. Same goes for PyPi and cran ... I just don't have time for this :(

**Comment by jmchilton** [comment]
@bgruening Thank for your concern - I'm still going to merge it because I think this is a very solid step above of what anaconda-verify offers. I'd encourage you to try it out with your recipes and consider it adopting it as part of the conda-forge stack. If y'all build something else or go in another direction - keep me posted and I will try to leverage it.

As for the more lofty points - auto-converting everything in bioconductor for conda sounds like a great plan. I'm not the one to do that - but it would be great to see.

**Comment by bgruening** [comment]
> @bgruening Thank for your concern - I'm still going to merge it because I think this is a very solid step above of what anaconda-verify offers. I'd encourage you to try it out with your recipes and consider it adopting it as part of the conda-forge stack. If y'all build something else or go in another direction - keep me posted and I will try to leverage it.

I guess this means the only argument left is "but I want to compete"? ;)

> As for the more lofty points - auto-converting everything in bioconductor for conda sounds like a great plan. I'm not the one to do that - but it would be great to see.

Not sure why lofty, you propose here that a recipe can be auto-generated, linted and so on ... if you can do it for one recipe you can do it for all, regularly, automated.
I envision something where Galaxy tool devs can just choose a version available in conda and not care about creating these recipes because all are already there.

Please feel free to merge, just my 2 cents.
Thanks John!

**Comment by jmchilton** [comment]
There is an interesting meta-conversation to be had here about competition in open source - but I leveraged upstream and improved on it in this case for sure so I definitely don't feel bad about trying to compete in this case.

How about this though - if you give up on trying to compete with CWL, I'll promise to never touch a piece of the conda tool chain again :laughing:.

**Comment by bgruening** [comment]
Isn't CWL competing with us? They could have looked at Galaxy and build on top of it ... oh wait and WDL, that is way better than CWL I have heard ;)
But I'm sure if you put a few more years into this project it will be as good as Galaxy tools! :)

Ok, back to work! Thanks John for this discussion! I will try to inform you about new changes upstream.

**Pull request merged**
