### PR TITLE
replace 'r' channel with 'conda-forge'

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by jmchilton** [comment]
Thanks - is this for planemo-machine - do I need to do a release?

**Comment by bgruening** [comment]
No, planemo-machine has a different problem, I didn't have time to fix yet. This was just what I found by browsing through the code.

**Comment by jmchilton** [comment]
I meant planemo-monitor, sorry I haven't had a chance to look at it yet. It shouldn't be your responsibility to fix 😰. I'm putting it on my TODO list for this week.

**Comment by bgruening** [comment]
All, good I know what you meant ... I will also try to look at it. It seems Galaxy does not catch an error at the moment and crashes.
Don't feel stressed :)

**Pull request merged**
