### PR TITLE
Various XSD Changes

### PR DESCRIPTION
**Pull request by jmchilton**
See individual commits.

### CODE REVIEW

**Comment by bgruening** [comment]
:+1: nice - Thanks!

**Comment by peterjc** [comment]
So this should fix #567 and #574 - sounds good :)

**Comment by peterjc** [comment]
I'm trying this on my tools today - there are some XSD failures which I need to look at to decide if they are my problems (real errors) or oversights in the XSD (false positives).

**Comment by jmchilton** [comment]
Awesome - thanks for all the help @peterjc.

**Pull request merged**
