### PR TITLE
Fix links

### PR DESCRIPTION
**Pull request by nsoranzo**
that reference a renamed master branch.

Also:
- Remove some more master references
- Update "standards" git submodule

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]

**Comment by mvdbeek** [comment]
Thank you @nsoranzo!

**Comment by nsoranzo** [comment]
Speaking of master branch, any chance we change the default branch for this repo https://github.com/galaxyproject/planemo/issues/1342 ?

**Comment by mvdbeek** [comment]
Yes, I think we should!

**Comment by nsoranzo** [comment]
I'd do it, but I don't have admin rights on this repo :)
Unless you'd like to have also @jmchilton's approval?

**Comment by mvdbeek** [comment]
I can rename the repo, but there's a lot of link updating to do, no ?

**Comment by nsoranzo** [comment]
> First thing after GCC is done ? laughing

Works for me, thanks!

**Pull request merged**
