### PR TITLE
Fix parsing of training ``metadata.yaml`` files

### PR DESCRIPTION
**Pull request by nsoranzo**
Fix https://github.com/galaxyproject/planemo/issues/1415 .

### CODE REVIEW

**Review by bernt-matthias — COMMENTED** [review]
Do we test or should we somehow test that the generated yaml file is valid (wrt to a schema)? Does GTN has one?  Should we request one?

I kind of do not understood why those internal (variable) names need to be renamed instead of just changing the display or giving a proper definition. But this is a different question.

**Review by bernt-matthias — APPROVED** [review]
Apart from this more general question the PR seems fine.

**Comment by hexylena** [comment]
> Do we test or should we somehow test that the generated yaml file is valid (wrt to a schema)? Does GTN has one? Should we request one?

the gtn has one, yes. but we are also considering alternative implementations that would be more integrated into the GTN, so, i'm not sure if it's worth the effort.

the schema is here: https://github.com/galaxyproject/training-material/blob/main/bin/schema-tutorial.yaml, but it does some non-standard things (namely replacing keywords like `CONTRIBUTORS` with their associated key upon parsing, and the 'examples' key that isn't part of kwalify, because those lists are also controlled but in separate data sources.)

We could emit a proper schema at an api endpoint that would be up-to-date if need be. 

> I kind of do not understood why those internal (variable) names need to be renamed

for me it would've been equivalent, yes, but i can see wanting to be sure all references are updated correctly.

**Comment by nsoranzo** [comment]
> > I kind of do not understood why those internal (variable) names need to be renamed
> 
> for me it would've been equivalent, yes, but i can see wanting to be sure all references are updated correctly.

Indeed, keeping variable names synced with the corresponding references was easy enough.

**Pull request merged**
