### PR TITLE
Add support for automatic repo creation

### PR DESCRIPTION
**Pull request by erasche**
Should this be on by default? That's my only real question. If planemo can't find the target repository, it'll automatically create one.

Depends on bioblend > https://github.com/galaxyproject/bioblend/pull/124

### CODE REVIEW

**Comment by jmchilton** [comment]
Yeah - my preference would be we not be automatically creating stuff by default. I would prefer a `-f/--force` flag on ``shed_upload`` and a separate ``shed_create`` action (though we can deal with the separate action post PR). Is this okay with you?

**Comment by erasche** [comment]
Yep, absolutely. Give me a few minutes and I'll have it updated!

**Comment by martenson** [comment]
+1 with John, create repos carefully as they cannot be uncreated :)

**Comment by erasche** [comment]
@jmchilton okay, repo creation is now off by default and optional. 

I'll make a separate PR with shed repo creation (though that starts to overlap with parsec)

**Comment by erasche** [comment]
@jmchilton okay, human names are now in use. `.shed.yml`s look like:

```yaml
name: gatk2
owner: iuc
description: The Genome Analysis Toolkit in Version 2
long_description: |
  The Genome Analysis Toolkit or GATK is a software package developed
  at the Broad Institute to analyse next-generation resequencing data. The toolkit
  offers a wide variety of tools, with a primary focus on variant discovery and
  genotyping as well as strong emphasis on data quality assurance. Its robust architecture,
  powerful processing engine and high-performance computing features make it capable
  of taking on projects of any size.

  http://www.broadinstitute.org/gatk/about/
  
  Repository-Maintainer: Bjoern Gruening, Nicola Soranzo and Jim Johnson
  Repository-Development: https://github.com/galaxy-iuc/tool_shed
type: unrestricted
categories:
    - Sequence Analysis
```

the category name must match precisely (capitalisation/spaces aren't stripped).

**Comment by erasche** [comment]
Oh, lovely, now coveralls is kvetching at me in addition to the linters. 

@jmchilton afaict none of the toolshed *interactions* are actually under test, and I'm not keen to write those...

**Comment by jmchilton** [comment]
Ignore coveralls - it is annoying.

**Comment by erasche** [comment]
@jmchilton anything else you want for this PR?

**Comment by jmchilton** [comment]
Not at first glace - this looks pretty awesome - thanks! I want to find some time to actually play with it before merging though.

@martenson You have thought a lot more than me about this issue - does this seem right to you? Do you feel like the correct things are being stored in `.shed.yml` in the correct format.

**Comment by erasche** [comment]
@jmchilton sure, no rush!

**Comment by martenson** [comment]
@jmchilton I think it is a good start but we know the target is moving. We are not creating standard yet, just exploring.

**Comment by erasche** [comment]
@jmchilton okay, that bug in `type` is actually upstream in https://github.com/galaxyproject/galaxy/pull/31

**Comment by jmchilton** [comment]
Crap - I merged the commits with a real ``merge`` so the PR would close when I pushed but then I rebased things out of vanity and the merge information got lost. Sorry about that - the commits are nonetheless in there - I hope that is okay.

**Comment by erasche** [comment]
No worries! Also, thanks for adding the test case. I'll make sure my future PR make some attempts to include those :)

**Pull request closed without merging**
