### PR TITLE
when repo update is ok but metadata is not put it in 'skipped' category

### PR DESCRIPTION
**Pull request by martenson**
this will help with Jenkins tracking

### CODE REVIEW

**Comment by erasche** [comment]
Skipped? Not sure I agree eith that. If metadata id failing, tjat should be a failure yes?

**Comment by martenson** [comment]
I was always confused by this. The command did everything right but then .shed yml does not have 'description' in it and that should cause it to fail?

**Comment by nsoranzo** [comment]
Fixing `.shed.yml` seems the best solution to me, the synopsis/short description is mandatory.

**Comment by erasche** [comment]
> I was always confused by this. The command did everything right but then .shed yml does not have 'description' in it and that should cause it to fail?

yep ;) making a fix mandatory is the best way to ensure it gets done

**Comment by peterjc** [comment]
Making the synopsis/short description is mandatory seems sensible from an IUC standards point of view, so +1 on that idea.

**Comment by jmchilton** [comment]
``shed_upload`` should work without it and so should ``update --skip_metadata``, find if updating the metadata require a description though - that seems reasonable.

**Pull request closed without merging**
