### PR TITLE
Add ability to test data manager tools

### PR DESCRIPTION
**Pull request by mvdbeek**
xref https://github.com/galaxyproject/galaxy/pull/7331, ~~needs at least a single test~~

### CODE REVIEW

**Comment by mvdbeek** [comment]
Alright, this works nicely, but we'll need to wait for https://github.com/galaxyproject/galaxy/pull/7331 and a new galaxy-lib release.

**Comment by jmchilton** [comment]
New galaxy-lib released, is this ready to go? I triggered a Travis rebuild. Sorry for the delay @mvdbeek.

**Comment by nsoranzo** [comment]
We need to update `requirements.txt` to require `galaxy-lib>=19.5.0`

**Comment by jmchilton** [comment]
Hmm... we need to add some sort of fallback for interface compatibility or update Planemo. I'll see if I can figure this out today...

Exception [verify() got an unexpected keyword argument 'get_filename'], Traceback [['Traceback (most recent call last):\n', '  File "/home/travis/build/galaxyproject/planemo/.tox/py36-quick/lib/python3.6/site-packages/click/testing.py", line 326, in invoke\n    cli.main(args=args or (), prog_name=prog_name, **extra)\n', '  File "/home/travis/build/galaxyproject/planemo/.tox/py36-quick/lib/python3.6/site-packages/click/core.py", line 717, in main\n    rv = self.invoke(ctx)\n', '  File "/home/travis/build/galaxyproject/planemo/.tox/py36-quick/lib/python3.6/site-packages/click/core.py", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n', '  File "/home/travis/build/galaxyproject/planemo/.tox/py36-quick/lib/python3.6/site-packages/click/core.py", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n', '  File "/home/travis/build/galaxyproject/planemo/.tox/py36-quick/lib/python3.6/site-packages/click/core.py", line 555, in invoke\n    return callback(*args, **kwargs)\n', '  File "/home/travis/build/galaxyproject/planemo/.tox/py36-quick/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func\n    return ctx.invoke(f, obj, *args, **kwargs)\n', '  File "/home/travis/build/galaxyproject/planemo/.tox/py36-quick/lib/python3.6/site-packages/click/core.py", line 555, in invoke\n    return callback(*args, **kwargs)\n', '  File "/home/travis/build/galaxyproject/planemo/planemo/cli.py", line 195, in handle_blended_options\n    return f(*args, **kwds)\n', '  File "/home/travis/build/galaxyproject/planemo/planemo/commands/cmd_test.py", line 87, in cli\n    test_data = engine.test(runnables)\n', '  File "/home/travis/build/galaxyproject/planemo/planemo/engine/interface.py", line 82, in test\n    test_case_data = test_case.structured_test_data(run_response)\n', '  File "/home/travis/build/galaxyproject/planemo/planemo/runnable.py", line 256, in structured_test_data\n    self._check_output(output_id, output_value, output_test)\n', '  File "/home/travis/build/galaxyproject/planemo/planemo/runnable.py", line 314, in _check_output\n    output_test,\n', '  File "/home/travis/build/galaxyproject/planemo/planemo/test/_check_output.py", line 43, in check_output\n    verify_extra_files=None,\n', "TypeError: verify() got an unexpected keyword argument 'get_filename'\n"]]

**Comment by mvdbeek** [comment]
Alright, it's green!

**Comment by jmchilton** [comment]
Amazing! Of course as always, but still just incredible and so essential. Thanks so much!

**Comment by nsoranzo** [comment]
Fantastic! Should we update https://github.com/galaxyproject/tools-iuc/blob/master/.travis.yml#L96 ?

**Comment by mvdbeek** [comment]
We'll also need a new planemo release, but maybe we can wait for https://github.com/galaxyproject/planemo/pull/931

**Comment by jmchilton** [comment]
We have got to get that gemini data manager PR merged and pushed - I'm going to just release as is right now, hope that is okay.

**Comment by mvdbeek** [comment]
Of course!

**Comment by jmchilton** [comment]
Planemo 0.59.0 has been released - thanks all! This is incredible.

**Pull request merged**
