### PR TITLE
Update cwltool and galaxy-lib dependencies for Python 3.7

### PR DESCRIPTION
**Pull request by nsoranzo**
Fix https://github.com/galaxyproject/planemo/issues/863 .

Need a release which includes https://github.com/common-workflow-language/cwltool/pull/831 .

### CODE REVIEW

**Comment by nsoranzo** [comment]
The 4 failing tests will be fixed by https://github.com/galaxyproject/galaxy-lib/pull/129 , a new `galaxy-lib` release and a corresponding update to `requirements.txt`.

**Comment by jmchilton** [comment]
I worried about this - cwltool underwent significant API breaking changes. I'll try to find some time to sit down and see if I can work through them.

**Comment by jmchilton** [comment]
I'm going to cherry-pick bad810a308f2cd60e1648594f3edba21a8219aeb into master though - I hope that is okay.

**Comment by nsoranzo** [comment]
Go ahead with the cherry-pick!

**Pull request merged**
