### PR TITLE
Make splitting job and test files optional

### PR DESCRIPTION
**Pull request by mvdbeek**
I think that makes writing tests easier and I think @bgruening agrees (https://github.com/galaxyproject/training-material/pull/2021#discussion_r464233812)

### CODE REVIEW

**Comment by jmchilton** [comment]
I'm totally fine hiding this behind a flag and I think I generally agree the single file version is simpler and should perhaps be best practice. I had this https://github.com/galaxyproject/planemo/pull/1052 in mind when I implemented this - I wanted to build some more support and documentation running workflows via Planemo. In that context, the standalone jobs are more useful as examples. We don't need to complicate testing because of my side quest though.

**Comment by mvdbeek** [comment]
Sounds like `planemo run` could also (optionally ?) output a runnable script like workflow2executable does ... that would be some nice convergence.

**Comment by jmchilton** [comment]
I tried to rebase your branch in https://github.com/galaxyproject/planemo/pull/1064/files but somehow it lost the commit author information 😢.

**Comment by mvdbeek** [comment]
No worries, that's fine.

**Comment by bgruening** [comment]
> Sounds like planemo run could also (optionally ?) output a runnable script like workflow2executable does ... that would be some nice convergence.

That would be great! However, not sure this should be part of planemo run. How do we structure all the workflow-run functionality? It would be super great to look up the invocations, get a link to the reports, restart all failing jobs in a workflow. @simonbray has some functionality in his gxwf project. But we are struggling with how we can fit this back into planmo from the CLI point of view.

**Pull request closed without merging**
