### PR TITLE
Allow outputing test results as allure framework results.

### PR DESCRIPTION
**Pull request by jmchilton**
Implements #1113.

xref http://allure.qatools.ru/

Quick Usage:

```
brew install allure
# Convert a Planemo/Ephemeris tool_test_outpt.json into a allure results directory 
planemo test_reports --test_output_allure allure_results/ ~/tool_test_outpt.json
# Generate a static site from that.
allure generate --clean allure_results/
# Serve and open with a browser (allure has a little shortcut for this)
allure open allure-repors/
```

---

Landing summary.

Screen Shot 2020-12-16 at 1 12 29 AM

---

Can dig into "Categories" and filter by exception vs failure:

Screen Shot 2020-12-16 at 1 26 34 AM

---

Category view group similar problems together:

Screen Shot 2020-12-16 at 1 28 21 AM

---

Screen Shot 2020-12-16 at 1 12 45 AM

---

Suite view allows digging into tools -> versions -> test index. Clicking a test allows access to a lot of data collected for debugging the problem.

Screen Shot 2020-12-16 at 1 15 46 AM

---

Pretty graphs that don't do a whole lot in our context.

Screen Shot 2020-12-16 at 1 15 57 AM

---

Pretty timeline that doesn't do a whole lot in our context.

Screen Shot 2020-12-16 at 1 16 26 AM

### CODE REVIEW

**Comment by bgruening** [comment]
That is pretty cool!

John is this `--test_output_allure allure` not redundant? Should this be `--test_output allure`?

**Comment by mvdbeek** [comment]
That is in line with `--test_output_markdown`, `--test_output_xunit` etc.

**Comment by bgruening** [comment]
And is this not redundant? Having `--test_output_allure` and the positional argument `allure` seems unnecessary to me. Should I open another issue about that?

**Comment by jmchilton** [comment]
Here allure is the directory that is being created, I don't think things are redundant. I'll update the example commands to clarify that.

**Comment by bgruening** [comment]
Thanks @jmchilton for the explanation!

**Pull request merged**
