### PR TITLE
sort failing tests to top first

### PR DESCRIPTION
**Pull request by bernt-matthias**
because for huge reports it gets annoying to spot the failing tests.

### CODE REVIEW

**Comment by mvdbeek** [comment]
Have you tried planemo from the master branch already ?

**Comment by bernt-matthias** [comment]
> Have you tried planemo from the master branch already ?

No. Do you think that something changed in this matter.

**Comment by bernt-matthias** [comment]
Just checked. `merge_test_reports` does not sort failing tests to the top. Even if `test` sorts the output (which would also be handy) this would still be necessary here. 

But maybe sorting would be even more appropriate here: https://github.com/galaxyproject/planemo/blob/3201c415a5d637984620d86b07bb9407d33833b5/planemo/reports/build_report.py#L20

(maybe also for other report type) then also `test` would be covered.

**Comment by bernt-matthias** [comment]
like so. we would just need to decide if we want to treat all outputs and the summary this way. In particular for the summary I do not particularly like it.

**Comment by mvdbeek** [comment]
have you looked at the html test report ?

**Comment by bernt-matthias** [comment]
I see.. nice.. even if I needed a while until I discovered that `Errored Tests` and `Passed Tests` can be clicked to be unfolded.

**Comment by mvdbeek** [comment]
Ah, that's a CSS problem I just haven't had the time to look at. Really should do that though.

**Comment by mvdbeek** [comment]
(It looks better on chrome)

**Pull request closed without merging**
