### PR TITLE
Adding shed_build command to build tarballs.

### PR DESCRIPTION
**Pull request by kellrott**
This is an attempt to build shed tarballs without needing to log into the shed server or do an upload.

### CODE REVIEW

**Comment by jmchilton** [comment]
This looks pretty solid, thanks @kellrott. I'll add some tests.

**Comment by peterjc** [comment]
Is this functionally like setting up a alias for ``planemo shed_upload --tar_only PACKAGE``?

**Comment by kellrott** [comment]
`planemo shed_upload --tar_only ` still tries to log in

**Comment by peterjc** [comment]
Understood - this sounds like a useful addition then (and might mean we can drop the ``--tar_only`` option from ``planemo shed_upload`` later on).

**Pull request merged**
