### PR TITLE
Xunit improvements

### PR DESCRIPTION
**Pull request by erasche**
- Refactors XUnit report templates into a single more generic template. (http://stackoverflow.com/a/9691131 good resource for what fields are available)
- Unrelated mktemp -> mkstemp
- Include timings in shed_diff (not useful but hey, neato)
- Include diffs in shed_diff (hella useful)

### CODE REVIEW

**Comment by jmchilton** [comment]
Super awesome @erasche.

**Comment by bgruening** [comment]
Nice!!!!
:+1:

**Comment by erasche** [comment]
Fixed test cases.

**Comment by martenson** [comment]
Thanks Eric.

**Pull request merged**
