### PR TITLE
First crack at containers documentation and related usability improvements

### PR DESCRIPTION
**Pull request by jmchilton**
- Implement ``planemo lint --biocontainer`` to mirror ``planemo lint --conda_requirements``. Just checks that a tool is ready to go with best practice namespaces for BioContainers tools.
- Implement test case for new linting flag.
- Add new section of documentation to advanced tool topics for containers. Work through examples of both an existing working container (seqtk) and one that must be built on the fly. Demonstrate ``planemo mull``.
- Hack around a bug in Conda 4.2 that makes it so ``planemo mull`` doesn't work out of the box on Mac OS X.
- Add more options and more documentation to the ``planemo mull`` command.

xref https://github.com/galaxyproject/training-material/issues/232

### CODE REVIEW

**Comment by bgruening** [comment]
Reads very well John! Wondering if this not also should be part of the Admin Docs in Galaxy.

**Comment by jmchilton** [comment]
There should be corresponding admin docs in Galaxy discussing how to use them from a deployers perspective for sure. Those docs shouldn't really mention Planemo. This is developer-centric documentation that covers Planemo and doesn't even mention ``enable_beta_mulled_containers`` or ``containers_resolvers_config_file`` - the Galaxy options.

I don't think the Galaxy side is quite ready for detailed documentation like this - I think we need some GUI tools, scripting, and a broad set of tools that have containers known to work first.

**Comment by bgruening** [comment]
> I don't think the Galaxy side is quite ready for detailed documentation like this - I think we need some GUI tools, scripting, and a broad set of tools that have containers known to work first.

Might, can be. But the first part is also interesting for admins that want to know how these things work internally. But yes, this has time. just wanted to say. this looks really good!!!

**Comment by jmchilton** [comment]
Yeah - I appreciate the review and the note about documentation. I have created a Galaxy issue for tracking this here https://github.com/galaxyproject/galaxy/issues/3710. Thanks as always and have . a great weekend.

I'm closing this PR because I merged directly after fixing the documentation problems.

**Pull request closed without merging**
