### PR TITLE
Nice makefile help

### PR DESCRIPTION
**Pull request by erasche**
As promised in https://github.com/galaxyproject/galaxy/pull/1824

### CODE REVIEW

**Comment by jmchilton** [comment]
Clever :smile:

**Comment by jxtx** [comment]
Except that `grep -P` is a gnuism, not posix, doesn't work on os x.

**Comment by erasche** [comment]
@jxtx right, people use OSX. I'll try and re-write without it.

**Comment by jxtx** [comment]
I might be tilting at windmills, but I must fight GNUisms where I find them. Simple fix in #419.

**Comment by erasche** [comment]
Thanks @jxtx, I appreciate the cross-platform fix! :)

**Pull request merged**
