### PR TITLE
Fix linting of tool URLS

### PR DESCRIPTION
**Pull request by nsoranzo**

### CODE REVIEW

**Comment by jmchilton** [comment]
Thanks for the fix - I'm pushing out a new release.

**Comment by nsoranzo** [comment]
Thanks! This should fix e.g. https://travis-ci.org/TGAC/earlham-galaxytools/builds/153570631#L911

**Comment by nsoranzo** [comment]
Update: the above Travis build was indeed fixed with a restart after the new Planemo release, thanks @jmchilton!

**Comment by jmchilton** [comment]
Cool beans - glad to hear it.

**Pull request merged**
