### PR TITLE
Updated docs for serve command

### PR DESCRIPTION
**Pull request by lparsons**
Added info about the use of virtualenv to the serve command docs.

### CODE REVIEW

**Comment by jmchilton** [comment]
Awesome, thanks!

**Comment by jmchilton** [comment]
Wait - actually that file is auto-generated. I'll make the change - sorry.

**Comment by lparsons** [comment]
Ooops! Sorry about that.

**Comment by lparsons** [comment]
Where is that text in the code? I can see where the options help comes from, but the the general command help.

**Pull request merged**
