### PR TITLE
Workflow linting

### PR DESCRIPTION
**Pull request by bedroesb**
Workflow linting that checks for:
- tags attribute
- annotation attribute
- tools in testtoolshed

Usage: planemo workflow_lint [OPTIONS] WORKFLOW_PATH

Options:
  --topic_name TEXT  Topic of the tutorial where this workflow belongs to.
  --help             Show this message and exit.

Example if topic_name is given as option and this can not be found in the tags attribute:
```
planemo workflow_lint --topic_name test main_workflow.ga
---------------------------------------------------------
Workflow 'Clustering 3K PBMCs With Scanpy' has 1 problem(s) because:
1. The 'tags' attribute is missing. Please add:
"tags": [
	"test"
]
---------------------------------------------------------

```
Example if used with travis at GTN:
```
Checking ./topics/computational-chemistry/tutorials/analysis-md-simulations/workflows/main_workflow.ga
Workflow is ok
Checking ./topics/computational-chemistry/tutorials/cheminformatics/workflows/_main_workflow.ga
---------------------------------------------------------
Workflow 'CTB Workflow' has 11 problem(s) because:
1. Step 11 has a tool from the testtoolshed.
2. Step 13 has a tool from the testtoolshed.
3. Step 19 has a tool from the testtoolshed.
4. Step 39 has a tool from the testtoolshed.
5. Step 31 has a tool from the testtoolshed.
6. Step 30 has a tool from the testtoolshed.
7. Step 29 has a tool from the testtoolshed.
8. Step 40 has a tool from the testtoolshed.
9. Step 2 has a tool from the testtoolshed.
10. Step 5 has a tool from the testtoolshed.
11. Step 44 has a tool from the testtoolshed.
---------------------------------------------------------
Checking ./topics/computational-chemistry/tutorials/md-simulation-gromacs/workflows/main_workflow.ga
Workflow is ok
```

### CODE REVIEW

**Comment by bgruening** [comment]
@bedroesb thanks for working on this!

**Comment by bedroesb** [comment]
@bgruening you are welcome!

**Comment by bedroesb** [comment]
I will first quickly test if I use this function in GTN travis check, it will act as expected.

**Comment by bedroesb** [comment]
@bgruening Everything works. Don't know if you have any recommendations?

**Comment by jmchilton** [comment]
Thanks for the first shot at this - cool stuff and good idea. Unfortunately, I had already started linting workflows in gxformat2 and exposing that work through Planemo was on my roadmap for this winter - so I've started backporting this work here into gxformat2 (https://github.com/galaxyproject/gxformat2/pull/28). I think we need to get away from opening workflow files in Planemo - it doesn't handle things in a systematic way - moving this logic there will do that.

My plan is to allow the use of gxformat2 directly or make it available through Planemo. In Planemo I don't think I want a new command, it should probably be folded into ``planemo lint``.

**Comment by bedroesb** [comment]
Ok no problem, good to hear about that. @bgruening should we close this PR and keep the linting on GTN for now for what it is or ?

**Comment by hexylena** [comment]
@bedroesb yep, let's close this and keep what we have in the training material for now, until the cool new stuff is available.

**Comment by bgruening** [comment]
Thanks @jmchilton!

**Comment by bedroesb** [comment]
Thank you, I would love to have a look at the training material part.

**Pull request closed without merging**
