### PR TITLE
Add a ro mount of the tool path's LCA

### PR DESCRIPTION
**Pull request by bernt-matthias**
compute the lowest common ancestor of

- the tool dirs
- the targets of all contained directories

and add it to the list of ro mounted volumes

May fix some of the currently failing CI tests: https://github.com/galaxyproject/tools-iuc/issues/4936 Problem is tools that use symlinks to other tools which does not work anymore due to https://github.com/galaxyproject/planemo/pull/1308

Not sure if this is a good way to fix

- [ ] should the same (or something analoguous) be done where I added the TODO?

### CODE REVIEW

**Comment by mvdbeek** [comment]
I don't think that's the right fix, how about `planemo test ----docker_extra_volume .` in the planemo-ci-action test command ?

**Comment by mvdbeek** [comment]
(https://github.com/galaxyproject/planemo/pull/1327)

**Comment by bernt-matthias** [comment]
> I don't think that's the right fix

Thought so :) ... wanted to make progress on this anyway :)

> how about planemo test --docker_extra_volume . in the planemo-ci-action test command

But this would need to be done by any `planemo test` command using containerized tests. 

Maybe we can use `.` as default for `--docker_extra_volume` (is this a parameter that can be specified multiple times)?

**Comment by mvdbeek** [comment]
> But this would need to be done by any planemo test command using containerized tests.

Only for those with a symlink to another tool. I am aware of only a single tool, ruvseq that does that.

**Comment by mvdbeek** [comment]
Or are you talking about pre 0.75.3 behavior ? We do mount the dir RO for the current runnable.

**Comment by bernt-matthias** [comment]
Superseded by https://github.com/galaxyproject/planemo/pull/1327

**Pull request closed without merging**
