### PR TITLE
Fix workflow_lint with list + check elements in collection

### PR DESCRIPTION
**Pull request by lldelisle**
This should solve #1309 
I would like to write tests. Should I make one directory per test with workflow and test file inside ? In the `tests/data/wf_repos`?
Thanks

### CODE REVIEW

**Comment by mvdbeek** [comment]
Yes, I think that's fine.

**Comment by lldelisle** [comment]
We ignore if tests are failing on the dev branch of galaxy right?

**Comment by mvdbeek** [comment]
Yes, those failing tests are probably related to one of the recent conda changes in Galaxy. Looks like there are some problems with local conda channels.

**Review by mvdbeek — APPROVED** [review]
That is super helpful, thank you so much @lldelisle!

**Comment by nsoranzo** [comment]
> Yes, those failing tests are probably related to one of the recent conda changes in Galaxy. Looks like there are some problems with local conda channels.

I tried to replicate this locally with:

```shell
PYTEST_TARGET=tests/test_cmd_test_conda.py::CmdTestCondaTestCase::test_local_conda_dependencies_version tox -e py37-unit-nonredundant-noclientbuild-noshed-gx-dev
```

but it passes for me even after removing `~/miniconda3/` .

**Pull request merged**
