### PR TITLE
Include workflow invocation status in test reports, generate html from markdown using markdown-it

### PR DESCRIPTION
**Pull request by mvdbeek**
This looks pretty similar to the old report (for tools). I didn't re-add the left-hand side, since I don't think this was too useful, but that should be easy to do if there is interest.
Here's how the report looks like for a failing workflow test:

Screenshot 2020-08-16 at 13 22 57

And this is a report from our weekly IUC tool testing.
Screenshot 2020-08-16 at 13 25 07

The html and markdown are generated from the same template, so the information is now on-par. This means a github action could for instance post the markdown for a tool test back to a PR (for PR testing) or an issue (for weekly workflow tests).
The reports now also contain tool parameters (both for tool and workflow tests).

There are still some things to be done, it would be nice to describe workflow steps in more detail, such as step type (input_dataset, input_collection, parameter, tool, subworkflow ?), collection type for dataset collection inputs, a test's doc attribute, execution time, job metrics, etc.

### CODE REVIEW

**Comment by mvdbeek** [comment]
Just checking out how the markdown report is rendered now:

# Tool Test Results (powered by Planemo)

## Executive Summary

| Test State | Count |
| ---------- | ----- |
| Total      | 1 |
| Passed     | 1 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


## Detailed Results

### Galaxy-Workflow-simple_test_workflow.ga_0

Test Passed



#### Workflow invocation details



0: test input:
  step_state: scheduled
  jobs:


1: Unnamed step:
  step_state: scheduled
  jobs:

  - job 1:

    - command_line: perl '/Users/mvandenb/src/galaxy/tools/filters/headWrapper.pl' '/Users/mvandenb/src/galaxy/database/files/1/8/9/dataset_189b7177-6914-446a-93ec-66f0720b9855.dat' 10 '/Users/mvandenb/src/galaxy/database/files/6/3/2/dataset_632860ca-07bd-401e-a8ef-c9bfb46de6a2.dat'
    - command_version: 
    - create_time: 2020-08-06T11:03:06.411348
    - exit_code: 0
    - external_id: 80881
    - galaxy_version: 20.05
    - history_id: 2891970512fa2d5a
    - id: 5729865256bc2525
    - inputs: {'input': {'id': '2891970512fa2d5a', 'src': 'hda', 'uuid': '189b7177-6914-446a-93ec-66f0720b9855'}}
    - job_messages: []
    - job_metrics: []
    - job_stderr: 
    - job_stdout: 
    - model_class: Job
    - outputs: {'out_file1': {'id': '5729865256bc2525', 'src': 'hda', 'uuid': '632860ca-07bd-401e-a8ef-c9bfb46de6a2'}}
    - params: {'__input_ext': '"txt"', '__workflow_invocation_uuid__': '"6775e946d7d411eaa988a683e74ed1f9"', 'chromInfo': '"/Users/mvandenb/src/galaxy/tool-data/shared/ucsc/chrom/?.len"', 'dbkey': '"?"', 'lineNum': '"10"'}
    - state: ok
    - stderr: 
    - stdout: 
    - tool_id: Show beginning1
    - tool_stderr: 
    - tool_stdout: 
    - update_time: 2020-08-06T11:03:09.091027
    - user_email: planemo@galaxyproject.org

2: Select last:
  step_state: scheduled
  jobs:

  - job 1:

    - command_line: perl '/Users/mvandenb/src/galaxy/tools/filters/tailWrapper.pl' '/Users/mvandenb/src/galaxy/database/files/6/3/2/dataset_632860ca-07bd-401e-a8ef-c9bfb46de6a2.dat' 1 '/Users/mvandenb/src/galaxy/database/files2/000/dataset_3.dat'
    - command_version: 
    - create_time: 2020-08-06T11:03:06.580401
    - exit_code: 0
    - external_id: 80943
    - galaxy_version: 20.05
    - history_id: 2891970512fa2d5a
    - id: 54f2a3a23292eb07
    - inputs: {'input': {'id': '5729865256bc2525', 'src': 'hda', 'uuid': '632860ca-07bd-401e-a8ef-c9bfb46de6a2'}}
    - job_messages: []
    - job_metrics: []
    - job_stderr: 
    - job_stdout: 
    - model_class: Job
    - outputs: {'out_file1': {'id': '54f2a3a23292eb07', 'src': 'hda', 'uuid': '924c7cc2-06eb-4702-bea6-c374f1617dcb'}}
    - params: {'__input_ext': '"txt"', '__workflow_invocation_uuid__': '"6775e946d7d411eaa988a683e74ed1f9"', 'chromInfo': '"/Users/mvandenb/src/galaxy/tool-data/shared/ucsc/chrom/?.len"', 'dbkey': '"?"', 'lineNum': '"1"'}
    - state: ok
    - stderr: 
    - stdout: 
    - tool_id: Show tail1
    - tool_stderr: 
    - tool_stdout: 
    - update_time: 2020-08-06T11:03:12.074555
    - user_email: planemo@galaxyproject.org

**Comment by mvdbeek** [comment]
With collapsible job sections:

# Tool Test Results (powered by Planemo)

## Executive Summary

| Test State | Count |
| ---------- | ----- |
| Total      | 1 |
| Passed     | 1 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


## Detailed Results

### Galaxy-Workflow-simple_test_workflow.ga_0

Test Passed



#### Workflow invocation details



0: test input:
  step_state: scheduled
  <details><summary>jobs:</summary>

  </details>
  


1: Unnamed step:
  step_state: scheduled
  <details><summary>jobs:</summary>

  - job 1:

    - command_line: perl '/Users/mvandenb/src/galaxy/tools/filters/headWrapper.pl' '/Users/mvandenb/src/galaxy/database/files/1/8/9/dataset_189b7177-6914-446a-93ec-66f0720b9855.dat' 10 '/Users/mvandenb/src/galaxy/database/files/6/3/2/dataset_632860ca-07bd-401e-a8ef-c9bfb46de6a2.dat'
    - command_version: 
    - create_time: 2020-08-06T11:03:06.411348
    - exit_code: 0
    - external_id: 80881
    - galaxy_version: 20.05
    - history_id: 2891970512fa2d5a
    - id: 5729865256bc2525
    - inputs: {'input': {'id': '2891970512fa2d5a', 'src': 'hda', 'uuid': '189b7177-6914-446a-93ec-66f0720b9855'}}
    - job_messages: []
    - job_metrics: []
    - job_stderr: 
    - job_stdout: 
    - model_class: Job
    - outputs: {'out_file1': {'id': '5729865256bc2525', 'src': 'hda', 'uuid': '632860ca-07bd-401e-a8ef-c9bfb46de6a2'}}
    - params: {'__input_ext': '"txt"', '__workflow_invocation_uuid__': '"6775e946d7d411eaa988a683e74ed1f9"', 'chromInfo': '"/Users/mvandenb/src/galaxy/tool-data/shared/ucsc/chrom/?.len"', 'dbkey': '"?"', 'lineNum': '"10"'}
    - state: ok
    - stderr: 
    - stdout: 
    - tool_id: Show beginning1
    - tool_stderr: 
    - tool_stdout: 
    - update_time: 2020-08-06T11:03:09.091027
    - user_email: planemo@galaxyproject.org
  </details>
  


2: Select last:
  step_state: scheduled
  <details><summary>jobs:</summary>

  - job 1:

    - command_line: perl '/Users/mvandenb/src/galaxy/tools/filters/tailWrapper.pl' '/Users/mvandenb/src/galaxy/database/files/6/3/2/dataset_632860ca-07bd-401e-a8ef-c9bfb46de6a2.dat' 1 '/Users/mvandenb/src/galaxy/database/files2/000/dataset_3.dat'
    - command_version: 
    - create_time: 2020-08-06T11:03:06.580401
    - exit_code: 0
    - external_id: 80943
    - galaxy_version: 20.05
    - history_id: 2891970512fa2d5a
    - id: 54f2a3a23292eb07
    - inputs: {'input': {'id': '5729865256bc2525', 'src': 'hda', 'uuid': '632860ca-07bd-401e-a8ef-c9bfb46de6a2'}}
    - job_messages: []
    - job_metrics: []
    - job_stderr: 
    - job_stdout: 
    - model_class: Job
    - outputs: {'out_file1': {'id': '54f2a3a23292eb07', 'src': 'hda', 'uuid': '924c7cc2-06eb-4702-bea6-c374f1617dcb'}}
    - params: {'__input_ext': '"txt"', '__workflow_invocation_uuid__': '"6775e946d7d411eaa988a683e74ed1f9"', 'chromInfo': '"/Users/mvandenb/src/galaxy/tool-data/shared/ucsc/chrom/?.len"', 'dbkey': '"?"', 'lineNum': '"1"'}
    - state: ok
    - stderr: 
    - stdout: 
    - tool_id: Show tail1
    - tool_stderr: 
    - tool_stdout: 
    - update_time: 2020-08-06T11:03:12.074555
    - user_email: planemo@galaxyproject.org
  </details>

**Comment by jmchilton** [comment]
That is so cool 😍

**Comment by mvdbeek** [comment]
This one skips rendering null job params and renders job params as a collapsible table:

# Tool Test Results (powered by Planemo)

## Executive Summary

| Test State | Count |
| ---------- | ----- |
| Total      | 1 |
| Passed     | 1 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


## Detailed Results

### Galaxy-Workflow-simple_test_workflow.ga_0

Test Passed



#### Workflow invocation details

<details><summary>Steps</summary>

0. **test input**:
  step_state: scheduled
  

1. **Show beginning1**:
  step_state: scheduled
  
    <details><summary>jobs:</summary>
  
    - job 1:

     | | |
     | - | - |
     | command_line | `perl '/Users/mvandenb/src/galaxy/tools/filters/headWrapper.pl' '/Users/mvandenb/src/galaxy/database/files/1/8/9/dataset_189b7177-6914-446a-93ec-66f0720b9855.dat' 10 '/Users/mvandenb/src/galaxy/database/files/6/3/2/dataset_632860ca-07bd-401e-a8ef-c9bfb46de6a2.dat'` |
     | create_time | `2020-08-06T11:03:06.411348` |
     | external_id | `80881` |
     | galaxy_version | `20.05` |
     | history_id | `2891970512fa2d5a` |
     | id | `5729865256bc2525` |
     | inputs | `{'input': {'id': '2891970512fa2d5a', 'src': 'hda', 'uuid': '189b7177-6914-446a-93ec-66f0720b9855'}}` |
     | model_class | `Job` |
     | outputs | `{'out_file1': {'id': '5729865256bc2525', 'src': 'hda', 'uuid': '632860ca-07bd-401e-a8ef-c9bfb46de6a2'}}` |
     | params | `{'__input_ext': '"txt"', '__workflow_invocation_uuid__': '"6775e946d7d411eaa988a683e74ed1f9"', 'chromInfo': '"/Users/mvandenb/src/galaxy/tool-data/shared/ucsc/chrom/?.len"', 'dbkey': '"?"', 'lineNum': '"10"'}` |
     | state | `ok` |
     | tool_id | `Show beginning1` |
     | update_time | `2020-08-06T11:03:09.091027` |
     | user_email | `planemo@galaxyproject.org` |
     
    </details>
  

2. **Select last**:
  step_state: scheduled
  
    <details><summary>jobs:</summary>
  
    - job 1:

     | | |
     | - | - |
     | command_line | `perl '/Users/mvandenb/src/galaxy/tools/filters/tailWrapper.pl' '/Users/mvandenb/src/galaxy/database/files/6/3/2/dataset_632860ca-07bd-401e-a8ef-c9bfb46de6a2.dat' 1 '/Users/mvandenb/src/galaxy/database/files2/000/dataset_3.dat'` |
     | create_time | `2020-08-06T11:03:06.580401` |
     | external_id | `80943` |
     | galaxy_version | `20.05` |
     | history_id | `2891970512fa2d5a` |
     | id | `54f2a3a23292eb07` |
     | inputs | `{'input': {'id': '5729865256bc2525', 'src': 'hda', 'uuid': '632860ca-07bd-401e-a8ef-c9bfb46de6a2'}}` |
     | model_class | `Job` |
     | outputs | `{'out_file1': {'id': '54f2a3a23292eb07', 'src': 'hda', 'uuid': '924c7cc2-06eb-4702-bea6-c374f1617dcb'}}` |
     | params | `{'__input_ext': '"txt"', '__workflow_invocation_uuid__': '"6775e946d7d411eaa988a683e74ed1f9"', 'chromInfo': '"/Users/mvandenb/src/galaxy/tool-data/shared/ucsc/chrom/?.len"', 'dbkey': '"?"', 'lineNum': '"1"'}` |
     | state | `ok` |
     | tool_id | `Show tail1` |
     | update_time | `2020-08-06T11:03:12.074555` |
     | user_email | `planemo@galaxyproject.org` |
     
    </details>
  

</details>

**Comment by mvdbeek** [comment]
We could also use the markdown as a basis for generating html:
Screenshot 2020-08-07 at 12 22 20

That's generated with [showdown](https://github.com/showdownjs/showdown).
If we did this we'd have the exact same information in the html report and the markdown ... what do you think ?

**Comment by mvdbeek** [comment]
Here's one of the weekly tool test runs as markdown: https://gist.github.com/mvdbeek/5ef5664bbaf2d84788ac946f95a35944

**Comment by mvdbeek** [comment]
And here's the generated html: https://gistpreview.github.io/?e86d334bff5ecfbf4e1f84428bc94aa2/test.html

**Comment by mvdbeek** [comment]
I think this is ready as a first pass, I'll keep working on this, but if anyone wants to merge this that'd be fine with me.

**Comment by jmchilton** [comment]
This is wonderful, amazing, and awesome! Thanks a bunch for all this work.

**Comment by simonbray** [comment]
It would be great if it could be made clearer that 'Passed tests' and 'Failed tests' can be clicked and expanded to show detailed information about the tests. Otherwise, for users that are used to the old style of reports, it looks like this information is simply no longer available.

image

**Comment by mvdbeek** [comment]
That's not how this looks like for me ... what browser are you using and can you upload the html ?

**Comment by simonbray** [comment]
Firefox 80.0.1. Here's the output: [tool_test_output.txt](https://github.com/galaxyproject/planemo/files/5262220/tool_test_output.txt) (uploaded with txt ext since github won't allow html for some reason).

**Comment by simonbray** [comment]
I checked with Chrome and it looks like this, which I'm guessing is the desired appearance:

image

**Comment by mvdbeek** [comment]
Yep, I think the CSS is slightly off here.

**Pull request merged**
