### PR TITLE
Create upload_data subcommand

### PR DESCRIPTION
**Pull request by simonbray**
Implement https://github.com/galaxyproject/planemo/issues/1104.

### CODE REVIEW

**Comment by simonbray** [comment]
@jmchilton would it be possible to merge this?

On another topic, could we have a new Planemo release prior to GCC? @wm75 and I would like to use some of the newest features in a training.

**Review by mvdbeek — APPROVED** [review]
Awesome, thanks @simonbray!

**Comment by mvdbeek** [comment]
@simonbray new release is on pypi -> https://pypi.org/project/planemo/0.74.4/

**Comment by simonbray** [comment]
Great, thanks so much @mvdbeek!

**Comment by bgruening** [comment]
Bioconda package and container available in 30min.

**Pull request merged**
