### PR TITLE
Try to fix planemo test workflow when output is collection with identical name

### PR DESCRIPTION
**Pull request by lldelisle**
See https://github.com/galaxyproject/iwc/pull/225

### CODE REVIEW

**Comment by lldelisle** [comment]
Any idea why the test is not failing?
What did I do wrong?

**Comment by mvdbeek** [comment]
It would have run in https://github.com/galaxyproject/planemo/actions/runs/6421040087/job/17434490532, but that was cancelled.

**Comment by mvdbeek** [comment]
And yeah, it's failing locally for me too and my commit fixes this.

**Comment by lldelisle** [comment]
Great!
Should I try to fix the CI into another PR?

**Comment by mvdbeek** [comment]
I think this is conda timing out, that probably needs to be fixed on the Galaxy or Conda side ...

**Comment by lldelisle** [comment]
Thanks for the fix.

**Comment by mvdbeek** [comment]
Thanks for the test, that made it easy!

**Pull request merged**
