### PR TITLE
Fix ``run_tests.sh`` invocation

### PR DESCRIPTION
**Pull request by nsoranzo**
Also:
- Drop support for Python 3.5
- Add support for Python 3.9
- Rebuild docs

### CODE REVIEW

**Comment by nsoranzo** [comment]
Depends on https://github.com/kislyuk/argcomplete/pull/332 and a new argcomplete release on PyPI.

**Comment by nsoranzo** [comment]
Ready for review!

BTW, it looks to me that all test jobs in `.circleci/config.yml` are already run in GitHub workflows, can we drop the file? @jmchilton

**Review by mvdbeek — APPROVED** [review]

**Comment by jmchilton** [comment]
There are a bunch of overlapping parameters to get more of these buggy tests working - I'd very much like to expand test coverage (more tests, more versions of Python, more versions of Galaxy, etc..) so I was working on trying to get those circleci tests working. I wouldn't delete the file - I'd like to keep working on it.

**Comment by jmchilton** [comment]
Thanks so much for the fix!

**Pull request merged**
