### PR TITLE
Account for new .txt, .md test outputs

### PR DESCRIPTION
**Pull request by erasche**

### CODE REVIEW

**Comment by peterjc** [comment]
Does it make sense to add these to ``.gitignore`` as well?

**Comment by erasche** [comment]
@peterjc yep, they shouldn't be included in your repository. Or did you mean a gitignore as part of planemo that I'm not aware of?

**Comment by nsoranzo** [comment]
I guess Peter means https://github.com/galaxyproject/planemo/blob/master/.gitignore , which I'd +1.

**Comment by erasche** [comment]
Done

**Comment by martenson** [comment]
:+1:

**Comment by peterjc** [comment]
Yes, that's what I had in mind with ``.gitignore`` - I do sometimes run ``planemo`` from the repository using relative or absolute paths to my tool repositories.

+1 on merging assuming the tests come back fine.

**Pull request merged**
