### PR TITLE
Implement container_register for tool repositories.

### PR DESCRIPTION
**Pull request by jmchilton**
xref - last bullet of #646

### CODE REVIEW

**Comment by peterjc** [comment]
Is it worth fixing the typo in the commit message?

**Comment by peterjc** [comment]
The documentation is somewhat cryptic without being familiar with the area, but that also means I can't suggest how to improve this:

```python
   """Register multi-requirement containers as needed.

    BioContainers publishes all Bioconda packages automatically as individual
    container images. These however are not enough for tools with multiple
    best-practice requirements. Such requirements should be recorded and published
    so that a container can be created and registered for these tools.
    """
```

**Comment by jmchilton** [comment]
@peterjc Agreed this is not documented well and I'm still trying to figure out how to describe what is going on. There was a bit of a conversation about this in the tools-iuc Gitter just now and there is some discussion on the README of [this repo](https://github.com/jmchilton/mulled-monitor) if you want to dig a little deeper. At a high level, the goal is that all tools that have Conda-ified requirement tags will automatically have containers registered and published quay.io/biocontainers for each unique combination of requirements. This new command opens a PR against a registry of such combinations that when merged will result in a container being published. I want to just monitor repositories though and take care of these details without intervention on a per tool basis - so to leverage this tool developers will just need to add their repository to the list in this file (https://github.com/jmchilton/mulled-monitor/blob/master/monitor.sh#L3). I'm going to present this as the GCC - so hopefully I figure out how to talk about this before then.

**Comment by bgruening** [comment]
Wuhu!!!!

**Comment by jmchilton** [comment]
Thanks @bgruening - I've updated #646 with your v2 mulled idea.

**Pull request merged**
